[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

# Handle JavaScript files
[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

# Handle CSS files  
[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css"

[build.environment]
  NODE_VERSION = "18"